# Generated by Django 5.1.2 on 2024-10-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('users', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='app',
            name='direction',
            field=models.TextField(max_length=400),
        ),
        migrations.AddField(
            model_name='app',
            name='stor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.appstors'),
        ),
    ]
